src/BAE_Brasil/Controllers/EmployerController.cs
using BAE_Brasil.Models.ViewModels;
using BAE_Brasil.Service;
using BAE_Brasil.Utils.Enums;
using Microsoft.AspNetCore.Mvc;

namespace BAE_Brasil.Controllers
{
    public class EmployerController : Controller
    {
        private readonly ICandidateFilterService _candidateFilterService;
        private readonly IAuthorizationPolicyEnforcementService _policyEnforcementService;
        
        public EmployerController(ICandidateFilterService candidateFilterService, 
            IAuthorizationPolicyEnforcementService policyEnforcementService)
        {
            _candidateFilterService = candidateFilterService;
            _policyEnforcementService = policyEnforcementService;
        }
        
        [HttpGet]
        public IActionResult SearchResumes()
        {
            _policyEnforcementService
                .SetCurrentSession(HttpContext.Session)
                .EnsureLoggedIn()
                .EnsureUserType(UserType.Empregador)
                .EnsureThatUserProfile(exists: true);
            
            return View();
        }

        public IActionResult SubmitSearchResumes(SearchCandidateViewModel searchCandidateVm)
        {
            var result = _candidateFilterService.Filter(searchCandidateVm);
            searchCandidateVm.UserProfiles = result;
            return View("SearchResumes", searchCandidateVm);
        }
    }
}

src/BAE_Brasil/Controllers/ProfileController.cs
using BAE_Brasil.Utils.Extensions;
using BAE_Brasil.Models.ViewModels;
using BAE_Brasil.Service;
using Microsoft.AspNetCore.Mvc;

namespace BAE_Brasil.Controllers
{
    public class ProfileController : Controller
    {
        private readonly IAuthorizationPolicyEnforcementService _authorizationPolicy;
        private readonly IUserProfileService _userProfileService;
        
        public ProfileController(
            IAuthorizationPolicyEnforcementService authorizationPolicy, IUserProfileService userProfileService)
        {
            _authorizationPolicy = authorizationPolicy;
            _userProfileService = userProfileService;
        }
        
        [HttpGet]
        public IActionResult Index()
        {
            _authorizationPolicy
                .SetCurrentSession(HttpContext.Session)
                .EnsureLoggedIn()
                .EnsureThatUserProfile(exists: true);

            var userProfileVm = _userProfileService.BuildUserProfileViewModel(HttpContext.Session.GetUserId().Value);
            return View(userProfileVm);
        }

        [HttpGet]
        public IActionResult Create()
        {
            _authorizationPolicy
                .SetCurrentSession(HttpContext.Session)
                .EnsureLoggedIn()
                .EnsureThatUserProfile(exists: false);

            return View(new CreateProfileViewModel
            {
                UserType = HttpContext.Session.GetUserType()
            });
        }

        [HttpPost]
        public IActionResult SubmitCreate(CreateProfileViewModel createProfileVm)
        {
            if (_userProfileService.CreateProfile(createProfileVm, ModelState, HttpContext.Session))
                return RedirectToAction("Index", "Home");

            return View("Create");
        }

        [HttpPost]
        public IActionResult SubmitCreateAddress(UserProfileViewModel userProfileVm)
        {
            if(_userProfileService.CreateAddress(userProfileVm, ModelState, HttpContext.Session))
                return RedirectToAction("Index");
            
            return View("Index");
        }
    }
}

src/BAE_Brasil/Controllers/ResumeController.cs
using BAE_Brasil.Models;
using BAE_Brasil.Utils.Extensions;
using BAE_Brasil.Models.ViewModels;
using BAE_Brasil.Service;
using BAE_Brasil.Utils.Enums;
using Microsoft.AspNetCore.Mvc;

namespace BAE_Brasil.Controllers
{
    public class ResumeController : Controller
    {
        private readonly IResumeService _resumeService;
        private readonly IAuthorizationPolicyEnforcementService _authorizationPolicy;

        public ResumeController(
            IResumeService resumeService, IAuthorizationPolicyEnforcementService authorizationPolicy)
        {
            _resumeService = resumeService;
            _authorizationPolicy = authorizationPolicy;
        }
        
        [HttpGet]
        public IActionResult Index()
        {
            _authorizationPolicy.SetCurrentSession(HttpContext.Session)
                .EnsureLoggedIn()
                .EnsureThatUserProfile(exists: true)
                .EnsureUserType(UserType.Candidato);
            
            var profileId = HttpContext.Session.GetProfileId().Value;
            
            if (!_resumeService.ResumeExists(profileId)) 
                return RedirectToAction("Create");
            
            var resumeVm = _resumeService.BuildResumeViewModel(profileId);
            return View(resumeVm);
        }

        [HttpGet]
        public IActionResult Create()
        {
            _authorizationPolicy.SetCurrentSession(HttpContext.Session)
                .EnsureLoggedIn()
                .EnsureThatUserProfile(exists: true)
                .EnsureUserType(UserType.Candidato);
                
            return View();
        }

        [HttpPost]
        public IActionResult SubmitCreate(CreateResumeViewModel createResumeVm)
        {
            var profileId = HttpContext.Session.GetProfileId().Value;

            if (_resumeService.CreateResume(createResumeVm, ModelState, profileId))
            {
                return RedirectToAction("Index");
            }
            return View("Create");
        }

        [HttpGet]
        public IActionResult AddProfessionalExperience()
        {
            _authorizationPolicy.SetCurrentSession(HttpContext.Session)
                .EnsureLoggedIn()
                .EnsureThatUserProfile(exists: true)
                .EnsureUserType(UserType.Candidato);

            return View();
        }
        
        [HttpPost]
        public IActionResult SubmitAddProfessionalExperience(ProfessionalExperience professionalExperience)
        {
            var profileId = HttpContext.Session.GetProfileId().Value;
            if (_resumeService.AddProfessionalExperience(professionalExperience, ModelState, profileId))
            {
                return RedirectToAction("Index");
            }
            return View("AddProfessionalExperience");
        }

        [HttpGet]
        public IActionResult AddDegree()
        {
            _authorizationPolicy.SetCurrentSession(HttpContext.Session)
                .EnsureLoggedIn()
                .EnsureThatUserProfile(exists: true)
                .EnsureUserType(UserType.Candidato);
                
            return View();
        }

        [HttpPost]
        public IActionResult SubmitAddDegree(Degree degree)
        {
            var profileId = HttpContext.Session.GetProfileId().Value;
            if (_resumeService.AddDegree(degree, ModelState, profileId))
            {
                return RedirectToAction("Index");
            }

            return View("AddDegree");
        }

        [HttpGet]
        public IActionResult AddLanguage()
        {
            _authorizationPolicy.SetCurrentSession(HttpContext.Session)
                .EnsureLoggedIn()
                .EnsureThatUserProfile(exists: true)
                .EnsureUserType(UserType.Candidato);
                
            return View();   
        }
        
        [HttpPost]
        public IActionResult SubmitAddLanguage(Language language)
        {
            var profileId = HttpContext.Session.GetProfileId().Value;
            if (_resumeService.AddLanguage(language, ModelState, profileId))
            {
                return RedirectToAction("Index");
            }

            return View("AddDegree");
        }
    }
}

src/BAE_Brasil/Controllers/UserController.cs
using BAE_Brasil.Utils.Extensions;
using BAE_Brasil.Models.ViewModels;
using BAE_Brasil.Service;
using Microsoft.AspNetCore.Mvc;

namespace BAE_Brasil.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserService _userService;

        public UserController(IUserService userService)
        {
            _userService = userService;
        }
        
        [HttpGet]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SubmitRegister(CreateUserViewModel createUserVm)
        {
            if (_userService.InsertUser(createUserVm, ModelState))
            {
                return RedirectToAction("Index", "Home");
            }

            return View("Register", createUserVm);
        }

        [HttpGet]
        public IActionResult Login()
        {
            ViewData.Add("isLoggedIn", HttpContext.Session.IsLoggedIn());
            return View();
        }

        [HttpPost]
        public IActionResult SubmitLogin(LoginViewModel loginVm)
        {
            if (_userService.Login(loginVm, ModelState, HttpContext.Session))
            {
                return RedirectToAction("Index", "Home");
            }
            return View("Login", loginVm);
        }

        [HttpGet]
        public IActionResult Logout()
        {
            _userService.Logout(HttpContext.Session);
            return RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public IActionResult Pop()
        {
            _userService.Pop();
            return RedirectToAction("Index", "Home");
        }
    }
}

src/BAE_Brasil/Views/Shared/LandingPartial.cshtml
@using System.Net.Http
@using BAE_Brasil.Utils.Enums
@using BAE_Brasil.Utils.Extensions
@using Microsoft.AspNetCore.Http
<div class="d-flex bg-light mt-3">
    <div id="content" class="d-flex flex-column justify-content-center">
        <div id="title">
            <div><h1 id="main-title" class="text-center">BAE BRASIL</h1></div>
            <div><h2 id="main-subtitle" class="text-center">Buscadora Acelerada de Empregos Brasil</h2></div>
        </div>
        @if (Context.Session.IsLoggedIn())
        {
            if (Context.Session.GetUserType() == UserType.Candidato)
            {
                <div class="mt-4 w-100 d-flex justify-content-center">
                    <a type="submit" href="#"
                        class="btn btn-primary font-weight-bold w-50">Buscar Vagas</a>
                </div>
            }
            else if (Context.Session.GetUserType() == UserType.Empregador)
            {
                <div class="mt-4 w-100 d-flex justify-content-center">
                    <a type="submit" asp-controller="Employer" asp-action="SearchResumes"
                       class="btn btn-primary font-weight-bold w-50">Buscar Candidatos</a>
                </div>
            }
        }
        else
        {
            <div class="mt-4 w-100 d-flex justify-content-center">
                <a type="submit" asp-controller="Employer" asp-action="SearchResumes"
                   class="btn btn-primary font-weight-bold w-50">Buscar Candidatos</a>
            </div>
            <div class="mt-4 w-100 d-flex justify-content-center">
                <a type="submit" href="#"
                   class="btn btn-primary font-weight-bold w-50">Buscar Vagas</a>
            </div>
        }

    </div>
    <div id="image" class="ml-4">
        <img src="files/employee.jpg" alt="pessoas trabalhando" id="empregados" width="300">
    </div>
</div>

src/BAE_Brasil/Views/Shared/_Layout.cshtml
@using BAE_Brasil.Utils.Extensions
@using BAE_Brasil.Utils.Enums
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - BAE Brasil</title>
    <script src="https://use.fontawesome.com/9e118a4f4a.js"></script>
    <link href="https://fonts.googleapis.com/css2?family=Comfortaa:wght@300;500;600;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BAE Brasil</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-white" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    @if (Context.Session.IsLoggedIn())
                    {
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="Profile" asp-action="Index">Meu Perfil</a>
                        </li>
                        @if (Context.Session.GetUserType() == UserType.Candidato)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="Resume" asp-action="Index">Meu Currículo</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-controller="" asp-action="">Vagas</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" 
                                   asp-controller="Employer" asp-action="SearchResumes">Candidatos</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="User" asp-action="Logout"
                               onclick="return confirm('Deseja mesmo sair de sua conta?')">Logout</a>
                        </li>
                    }
                    else
                    {
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="User" asp-action="Login">Login</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-controller="User" asp-action="Register">Registrar</a>
                        </li>
                    }
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top bg-dark text-white footer">
    <div class="container">
        &copy; 2021 - BAE Brasil - <a class="text-white" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.1/jquery.validate.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.11/jquery.validate.unobtrusive.min.js"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>